#!/bin/bash
SQ_ABUILD_PARTITION=/dev/vdb1
SQ_TEST_RUN_LIST=(
#workload_syscall_libmicro_socket
#workload_syscall_libmicro_process
#workload_syscall_libmicro_regular
#workload_syscall_libmicro_file
#workload_syscall_libmicro_memory
#
#workload_http_apache2_siege
########################P1 testcases##################
#workload_syscall_libmicro_contextswitch
#workload_syscall_lmbench_local
#workload_syscall_lmbench_syscall
#workload_syscall_lmbench_ctx
#
#workload_database_postgre_smallMem_pgbench_read_btrfs
#workload_database_postgre_smallMem_pgbench_read_ext4
#workload_database_postgre_smallMem_pgbench_read_xfs
#workload_database_postgre_smallMem_pgbench_rw_ext4
#workload_database_postgre_smallMem_pgbench_rw_xfs
#workload_database_mariadb_sysbench_read_btrfs
#workload_database_mariadb_sysbench_read_ext4
#workload_database_mariadb_sysbench_read_xfs
#
#################P3 testcases########################
#
io_block_generic_iozone_fsync_xfs
#io_block_generic_fio_random_fsync_btrfs
#io_block_generic_dbench4_async_btrfs
#io_block_generic_dbench4_fsync_btrfs
#io_block_generic_bonniepp_async_btrfs
#io_block_generic_bonniepp_fsync_btrfs
#workload_database_postgre_smallMem_pgbench_read_btrfs
#workload_database_postgre_smallMem_pgbench_rw_ext4
#io_block_generic_reaim_ioperf_btrfs
#io_block_generic_fio_async_btrfs

#_reboot_off
#workload_system_sysbench_sys
#workload_system_sysbench_sys
#_reboot_on
#workload_system_sysbench_sys

#workload_syscall_lmbench_mem
)
